//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipCommunicator.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SipCommunicator.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AutoAnswer disabled 的本地化字符串。
        /// </summary>
        internal static string AutoAnswer_Disabled {
            get {
                return ResourceManager.GetString("AutoAnswer_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoAnswer enabled 的本地化字符串。
        /// </summary>
        internal static string AutoAnswer_Enabled {
            get {
                return ResourceManager.GetString("AutoAnswer_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        internal static string CallState_Active {
            get {
                return ResourceManager.GetString("CallState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alerting 的本地化字符串。
        /// </summary>
        internal static string CallState_Alerting {
            get {
                return ResourceManager.GetString("CallState_Alerting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting 的本地化字符串。
        /// </summary>
        internal static string CallState_Connecting {
            get {
                return ResourceManager.GetString("CallState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Holding 的本地化字符串。
        /// </summary>
        internal static string CallState_Holding {
            get {
                return ResourceManager.GetString("CallState_Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        internal static string CallState_Idle {
            get {
                return ResourceManager.GetString("CallState_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incoming 的本地化字符串。
        /// </summary>
        internal static string CallState_Incoming {
            get {
                return ResourceManager.GetString("CallState_Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string CallState_Null {
            get {
                return ResourceManager.GetString("CallState_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Released 的本地化字符串。
        /// </summary>
        internal static string CallState_Released {
            get {
                return ResourceManager.GetString("CallState_Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminated 的本地化字符串。
        /// </summary>
        internal static string CallState_Terminated {
            get {
                return ResourceManager.GetString("CallState_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dail a number to tranfer: 的本地化字符串。
        /// </summary>
        internal static string CallState_TransferPrompt {
            get {
                return ResourceManager.GetString("CallState_TransferPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not disturb disabled 的本地化字符串。
        /// </summary>
        internal static string DND_Disabled {
            get {
                return ResourceManager.GetString("DND_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not disturb enabled 的本地化字符串。
        /// </summary>
        internal static string DND_Enabled {
            get {
                return ResourceManager.GetString("DND_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Login 的本地化字符串。
        /// </summary>
        internal static string MainForm_Login {
            get {
                return ResourceManager.GetString("MainForm_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Logout 的本地化字符串。
        /// </summary>
        internal static string MainForm_Logout {
            get {
                return ResourceManager.GetString("MainForm_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Mixer cannot initialize! \r\nCheck audio configuration and start again! 的本地化字符串。
        /// </summary>
        internal static string Message_AudioMixerInitializeError {
            get {
                return ResourceManager.GetString("Message_AudioMixerInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please create a default SIP account to login 的本地化字符串。
        /// </summary>
        internal static string Message_CreateAccountBeforeLogin {
            get {
                return ResourceManager.GetString("Message_CreateAccountBeforeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to delete SIP account {0} 的本地化字符串。
        /// </summary>
        internal static string Message_DeleteSipAccount {
            get {
                return ResourceManager.GetString("Message_DeleteSipAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete SIP account Confirm 的本地化字符串。
        /// </summary>
        internal static string Message_DeleteSipAccount_Caption {
            get {
                return ResourceManager.GetString("Message_DeleteSipAccount_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize Error 的本地化字符串。
        /// </summary>
        internal static string Message_InitializeError {
            get {
                return ResourceManager.GetString("Message_InitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Init SIP stack problem! \r\nPlease, check configuration and start again!&quot; 的本地化字符串。
        /// </summary>
        internal static string Message_SipStackInitializeError {
            get {
                return ResourceManager.GetString("Message_SipStackInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your speaker is muted 的本地化字符串。
        /// </summary>
        internal static string Microphone_Muted {
            get {
                return ResourceManager.GetString("Microphone_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your speaker is unmuted 的本地化字符串。
        /// </summary>
        internal static string Microphone_Unmuted {
            get {
                return ResourceManager.GetString("Microphone_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your speaker is unmuted 的本地化字符串。
        /// </summary>
        internal static string Speaker_Muted {
            get {
                return ResourceManager.GetString("Speaker_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your speaker is muted 的本地化字符串。
        /// </summary>
        internal static string Speaker_Unmuted {
            get {
                return ResourceManager.GetString("Speaker_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration error: 的本地化字符串。
        /// </summary>
        internal static string Status_RegistrationError {
            get {
                return ResourceManager.GetString("Status_RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registring... 的本地化字符串。
        /// </summary>
        internal static string Status_Registring {
            get {
                return ResourceManager.GetString("Status_Registring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your name is 的本地化字符串。
        /// </summary>
        internal static string Status_YourNameIs {
            get {
                return ResourceManager.GetString("Status_YourNameIs", resourceCulture);
            }
        }
    }
}
