//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipCommunicator.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SipCommunicator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bg02 {
            get {
                object obj = ResourceManager.GetObject("bg02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream congestion {
            get {
                return ResourceManager.GetStream("congestion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap contacts {
            get {
                object obj = ResourceManager.GetObject("contacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream dial {
            get {
                return ResourceManager.GetStream("dial", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gif026 {
            get {
                object obj = ResourceManager.GetObject("gif026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap id_card_24 {
            get {
                object obj = ResourceManager.GetObject("id_card_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap id_card_32_shadow {
            get {
                object obj = ResourceManager.GetObject("id_card_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kmixdocked_mute {
            get {
                object obj = ResourceManager.GetObject("kmixdocked_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_record_red_16 {
            get {
                object obj = ResourceManager.GetObject("media_record_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Microphone_Disabled {
            get {
                object obj = ResourceManager.GetObject("Microphone_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Microphone_Hot {
            get {
                object obj = ResourceManager.GetObject("Microphone_Hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Microphone_Normal {
            get {
                object obj = ResourceManager.GetObject("Microphone_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Microphone_Pressed {
            get {
                object obj = ResourceManager.GetObject("Microphone_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mix_headphone_16 {
            get {
                object obj = ResourceManager.GetObject("mix_headphone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mix_headphone_22 {
            get {
                object obj = ResourceManager.GetObject("mix_headphone_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mix_microphone {
            get {
                object obj = ResourceManager.GetObject("mix_microphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mix_microphone_22 {
            get {
                object obj = ResourceManager.GetObject("mix_microphone_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mix_microphone1 {
            get {
                object obj = ResourceManager.GetObject("mix_microphone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msn_phone {
            get {
                object obj = ResourceManager.GetObject("msn_phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msn_phone1 {
            get {
                object obj = ResourceManager.GetObject("msn_phone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_call {
            get {
                object obj = ResourceManager.GetObject("phone_call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_conference {
            get {
                object obj = ResourceManager.GetObject("phone_conference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_hang_up {
            get {
                object obj = ResourceManager.GetObject("phone_hang_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_hang_up_24 {
            get {
                object obj = ResourceManager.GetObject("phone_hang_up_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_hold {
            get {
                object obj = ResourceManager.GetObject("phone_hold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_pick_up {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_pick_up_24 {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_recall {
            get {
                object obj = ResourceManager.GetObject("phone_recall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_redirect {
            get {
                object obj = ResourceManager.GetObject("phone_redirect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_reject {
            get {
                object obj = ResourceManager.GetObject("phone_reject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_speaker {
            get {
                object obj = ResourceManager.GetObject("phone_speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_01 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_02 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_03 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_04 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_05 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_06 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_07 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_08 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_09 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PI_Diagona_Web_Application_04_10 {
            get {
                object obj = ResourceManager.GetObject("PI_Diagona_Web_Application_04_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ring {
            get {
                return ResourceManager.GetStream("ring", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ringback {
            get {
                return ResourceManager.GetStream("ringback", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings1 {
            get {
                object obj = ResourceManager.GetObject("settings1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sipphone_22 {
            get {
                object obj = ResourceManager.GetObject("sipphone_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sipphone_32 {
            get {
                object obj = ResourceManager.GetObject("sipphone_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_16 {
            get {
                object obj = ResourceManager.GetObject("telephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trkVolume_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("trkVolume_BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trkVolume_TrackerImage {
            get {
                object obj = ResourceManager.GetObject("trkVolume_TrackerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user2_16 {
            get {
                object obj = ResourceManager.GetObject("user2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user2_161 {
            get {
                object obj = ResourceManager.GetObject("user2_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume_Disabled {
            get {
                object obj = ResourceManager.GetObject("Volume_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume_Hot {
            get {
                object obj = ResourceManager.GetObject("Volume_Hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume_Normal {
            get {
                object obj = ResourceManager.GetObject("Volume_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume_Pressed {
            get {
                object obj = ResourceManager.GetObject("Volume_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
